spring.datasource.url=jdbc:postgresql://localhost:5432/api_monitor
spring.datasource.username=postgres
spring.datasource.password=rakshu@024

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=false